module.exports = function(nga, admin) {
		return nga.menu()
				.addChild(nga.menu()
						.icon('<span class="fa fa-bar-chart fa-fw"></span>')
						.title('Summary')
						.link('/summary')
				)
				.addChild(nga.menu()
						.title('Store')
						.icon('<span class="fa fa-shopping-cart fa-fw"></span>')
						// .active(function(path){return path.indexOf('/customers') === 0})
						.addChild(nga.menu(admin.getEntity('products'))
								.icon('<span class="fa fa-gift fa-fw"></span>')
								.title('Products')
						)
						.addChild(nga.menu(admin.getEntity('customers'))
								.active(function(path){return path.indexOf('/customers') === 0})
								.icon('<span class="fa fa-users fa-fw"></span>')
								.title('Customers')
						)
				// 		.addChild(nga.menu()
				// 				.title('Purchases')
				// 				.link('/purchases/list')
				// 				// .link('/customers/list?search={"has_ordered":"true"}')
				// 				.icon('<span class="fa fa-credit-card fa-fw"></span>'))
				)
				.addChild(nga.menu(admin.getEntity('posts'))
						.icon('<span class="fa fa-rss-square fa-fw"></span>')
						.title('Blog')
				)
				.addChild(nga.menu(admin.getEntity('shops'))
						.icon('<span class="fa fa-map-marker fa-fw"></span>')
						.title('Shops')
				)

		;
};
